"""
Public API for the interpreter.builtins package.

Exports:
  BUILTIN_METHODS  — nested dict: class_name -> selector -> function
  find_builtin()   — walks the inheritance chain to find a built-in method
  BlockEvaluator   — type alias for the eval_block callback

This code was generated by copilot AI
"""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING

from int.src.interpreter.builtins import block_methods, boolean_methods, integer_methods, nil_methods, object_methods
from int.src.interpreter.builtins import (
    string_methods,
)
from int.src.interpreter.builtins.helper_methods import _is_value_selector
from int.src.interpreter.exceptions import InterpreterError
from int.src.interpreter.runtime.sol_object import SolObject

if TYPE_CHECKING:
    from int.src.interpreter.class_registry import ClassRegistry
    from int.src.interpreter.runtime.sol_block import SolBlock

# Type alias: the callback the evaluator passes so built-in methods can
# trigger block evaluation without a circular import.
BlockEvaluator = Callable[["SolBlock", list[SolObject]], SolObject]

# Type alias for a single built-in method function.
BuiltinFn = Callable[
    [SolObject, list[SolObject], "ClassRegistry", BlockEvaluator],
    SolObject,
]

# ---------------------------------------------------------------------------
# Central dispatch table
# ---------------------------------------------------------------------------
BUILTIN_METHODS: dict[str, dict[str, BuiltinFn]] = {
    "Object":  object_methods.METHODS,
    "Nil":     nil_methods.METHODS,
    "Integer": integer_methods.METHODS,
    "String":  string_methods.METHODS,
    "Block":   block_methods.METHODS,
    "True":    boolean_methods.TRUE_METHODS,
    "False":   boolean_methods.FALSE_METHODS,
}


# ---------------------------------------------------------------------------
# Lookup function
# ---------------------------------------------------------------------------

def find_builtin(
    sol_class_name: str,
    selector: str,
    registry: ClassRegistry,
) -> BuiltinFn | None:
    """
    Walk the SOL26 inheritance chain to find a built-in method.

    Special case: Block + any 'value[:]...' selector is handled by the
    universal block_value_any handler regardless of arity.

    Parameters
    ----------
    sol_class_name : str
        Name of the class to start searching from.
    selector : str
        The message selector to look up.
    registry : ClassRegistry
        Used to resolve the parent class chain.

    Returns
    -------
    The built-in function, or None if not found anywhere in the chain.
    """
    # Special case: Block value selectors (any arity)
    if _is_value_selector(selector):
        current: str | None = sol_class_name
        while current is not None:
            if current == "Block":
                return block_methods._block_value
            try:
                parent = registry.get_class(current).parent
                current = parent.name if parent is not None else None
            except InterpreterError:
                break

    # Normal lookup — walk inheritance chain
    current = sol_class_name
    while current is not None:
        class_builtins = BUILTIN_METHODS.get(current, {})
        if selector in class_builtins:
            return class_builtins[selector]
        try:
            parent = registry.get_class(current).parent
            current = parent.name if parent is not None else None
        except InterpreterError:
            break

    return None


__all__ = [
    "BUILTIN_METHODS",
    "BlockEvaluator",
    "BuiltinFn",
    "find_builtin",
]
